sudo: required

services:
  - docker

before_install:
  - docker build -t huiying530/docker_react -f Dockerfile.dev .

script:
  - docker run --rm -e CI=true huiying530/docker_react npm run test -- --watch=false
