name: Deploy docker-react
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t docker_react/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true docker_react/react-test npm test

      - name: Generate deployment package
        run: zip -r docker_react.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-083597744184
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: docker_react.zip